# Generated by Django 2.2.11 on 2020-04-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200414_1930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
